# Generated by Django 5.2.9 on 2026-01-06 16:57

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='🎮', help_text='Эмодзи или название иконки Font Awesome', max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('game_type', models.CharField(choices=[('html5', 'HTML5 (Canvas/WebGL)'), ('javascript', 'Чистый JavaScript'), ('unity', 'Unity WebGL'), ('flash', 'Flash (устаревший)'), ('other', 'Другое')], default='html5', max_length=20, verbose_name='Тип игры')),
                ('game_file', models.FileField(help_text='Загрузите ZIP архив с игрой. Главный файл должен называться index.html', upload_to='games/files/%Y/%m/%d/', verbose_name='Файл игры (ZIP)')),
                ('thumbnail', models.ImageField(help_text='Рекомендуемый размер: 400x300px', upload_to='games/thumbnails/%Y/%m/%d/', verbose_name='Превью игры')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='games/screenshots/%Y/%m/%d/', verbose_name='Скриншот 1')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='games/screenshots/%Y/%m/%d/', verbose_name='Скриншот 2')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='games/screenshots/%Y/%m/%d/', verbose_name='Скриншот 3')),
                ('plays_count', models.IntegerField(default=0, verbose_name='Количество запусков')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум игра')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00 - бесплатная игра', max_digits=6, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(related_name='games', to='games.category', verbose_name='Категории')),
                ('tags', taggit.managers.TaggableManager(help_text='Через запятую', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
                'permissions': [('can_moderate_games', 'Может модерировать игры'), ('can_feature_games', 'Может отмечать игры как рекомендуемые')],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games.game')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('changelog', models.TextField(verbose_name='Список изменений')),
                ('game_file', models.FileField(upload_to='games/versions/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Счет')),
                ('time', models.IntegerField(default=0, verbose_name='Время (секунды)')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата рекорда')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('game', 'player')},
            },
        ),
    ]
