# Generated by Django 5.2.9 on 2026-01-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('player', 'Игрок'), ('developer', 'Разработчик'), ('moderator', 'Модератор')], default='player', max_length=20, verbose_name='Роль')),
                ('games_played', models.IntegerField(default=0, verbose_name='Сыграно игр')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий счет')),
                ('games_uploaded', models.IntegerField(default=0, verbose_name='Загружено игр')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
